services:
  - type: web
    name: telegram-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: API_ID
        value: 23656977
      - key: API_HASH
        value: 49d3f43531a92b3f5bc403766313ca1e
      - key: BOT_TOKEN
        value: 8398354970:AAGcDT0WAIUvT2DnTqyxfY1Q8h2b5rn-LIo
